# Template PHP Build

# This template allows you to validate your PHP application.
# The workflow allows running tests and code linting on the default branch.

pipelines:
  branches:
    master:
      - step:
          name: Our Very First Pipeline!
          script:
            - echo "Hello World!"
