{
 "title": "Application",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current User Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(app_user_count)" }
   ]
  },
  {
   "title": "Task Result Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(app_taskresult_count)" }
   ]
  },
  {
   "title": "Tasks assessment",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (app_taskresult_count)by (assessment)",
     "legendFormat": "{{assessment}}"
    }
   ]
  },
  {
   "title": "Task negative results",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (app_taskresult_count{assessment=~\"[0-4]\"}) without (assessment, user_id, id) / sum (app_taskresult_count{assessment=~\"[5-9]|10\"}) without (assessment, user_id, id)) * 100",
     "legendFormat": "{{task_title}} [{{task_id}}]"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(app_response_time_seconds_bucket[5m])) by (method, le))",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(app_response_time_seconds_bucket[5m])) by (le))",
     "legendFormat": "ALL"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by (method) (rate(app_request_count[5m]))",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Http Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum without (uri) (increase(app_request_count{code=~\"4..\"}[30s]))",
     "legendFormat": "Client {{method}} {{response_code}}"
    },
    {
     "expr": "sum without (uri) (increase(app_request_count{code=~\"5..\"}[30s]))",
     "legendFormat": "Server {{method}} {{response_code}}"
    }
   ]
  }
 ]
}