<?php
declare(strict_types=1);

namespace App\Virtual\Models;

use DateTime;

/**
 * @OA\Schema(
 *     title="Achievement",
 *     description="Achievement model",
 *     @OA\Xml(
 *         name="Achievement"
 *     )
 * )
 */
class Achievement
{

    /**
     * @OA\Property(
     *     title="ID",
     *     description="ID",
     *     format="int64",
     *     example=1
     * )
     *
     * @var integer
     */
    private int $id;

    /**
     * @OA\Property(
     *      title="Name",
     *      description="Name of the new achievement",
     *      example="A nice achievement"
     * )
     *
     * @var string
     */
    public string $name;

    /**
     * @OA\Property(
     *      title="Slug",
     *      description="Slug of the new achievement. Is autogenerated from name if not pass",
     *      example="a-nice-achievement"
     * )
     *
     * @var string
     */
    public string $slug;

    /**
     * @OA\Property(
     *      title="Description",
     *      description="Description of the new achievement",
     *      example="This is new achievement's description"
     * )
     *
     * @var string
     */
    public string $description;

    /**
     * @OA\Property(
     *      title="Expression",
     *      description="Language expression of the new achievement",
     *      example="exercise.taskResults.countWithCondition('assessment', 10)"
     * )
     *
     * @var string
     */
    public string $expression;

    /**
     * @OA\Property(
     *     title="Created at",
     *     description="Created at",
     *     example="2020-01-27 17:50:45",
     *     format="datetime",
     *     type="string"
     * )
     *
     * @var DateTime
     */
    private DateTime $created_at;

    /**
     * @OA\Property(
     *     title="Updated at",
     *     description="Updated at",
     *     example="2020-01-27 17:50:45",
     *     format="datetime",
     *     type="string"
     * )
     *
     * @var DateTime
     */
    private DateTime $updated_at;
}
